=== TheVirtuoid/FunWithJavaScript-Public/games/rpg/databases/schemas/CharacterClassData.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "CharacterClassData Schema",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "restrictions": {
      "type": "array",
      "items": {
        "type": "object"
      }
    },
    "levelData": {
      "type": "array",
      "items": {
        "type": "object"
      }
    },
    "id": {
      "type": "string"
    }
  }
}

=== TheVirtuoid/FunWithJavaScript-Public/games/rpg/databases/characterClass.json
[
  {
    "name": "Cleric",
    "description": "Clerics are those who have devoted themselves to the service of a deity, pantheon or other belief system. Most Clerics spend their time in mundane forms of service such as preaching and ministering in a temple; but there are those who are called to go abroad from the temple and serve their deity in a more direct way, smiting undead monsters and aiding in the battle against evil and chaos. Player character Clerics are assumed to be among the latter group.\nClerics fight about as well as Thieves, but not as well as Fighters. They are hardier than Thieves, at least at lower levels, as they are accustomed to physical labor that the Thief would deftly avoid. Clerics can cast spells of divine nature starting at 2nd level, and they have the power to Turn the Undead, that is, to drive away undead monsters by means of faith alone (refer to page 57 in the Encounter section for details).\nThe Prime Requisite for Clerics is Wisdom; a character must have a Wisdom score of 9 or higher to become a Cleric. They may wear any armor, but may only use blunt weapons (specifically including warhammer, mace, maul, club, quarterstaff, and sling).",
    "restrictions": [
      {
        "restrictionType": "minimum-ability",
        "type": "wisdom",
        "value": 9
      },
      {
        "restrictionType": "weapon-sharpness"
      }
    ],
    "levelData": [
      {
        "experiencePoints": 0,
        "hitPoints": "1d6",
        "otherAbilities": {
          "spells": [
            0,
            0,
            0,
            0,
            0,
            0
          ]
        }
      },
      {
        "experiencePoints": 1500,
        "hitPoints": "2d6",
        "otherAbilities": {
          "spells": [
            1,
            0,
            0,
            0,
            0,
            0
          ]
        }
      },
      {
        "experiencePoints": 3000,
        "hitPoints": "3d6",
        "otherAbilities": {
          "spells": [
            2,
            0,
            0,
            0,
            0,
            0
          ]
        }
      },
      {
        "experiencePoints": 6000,
        "hitPoints": "4d6",
        "otherAbilities": {
          "spells": [
            2,
            1,
            0,
            0,
            0,
            0
          ]
        }
      },
      {
        "experiencePoints": 12000,
        "hitPoints": "5d6",
        "otherAbilities": {
          "spells": [
            2,
            2,
            0,
            0,
            0,
            0
          ]
        }
      },
      {
        "experiencePoints": 24000,
        "hitPoints": "6d6",
        "otherAbilities": {
          "spells": [
            2,
            2,
            1,
            0,
            0,
            0
          ]
        }
      },
      {
        "experiencePoints": 48000,
        "hitPoints": "7d6",
        "otherAbilities": {
          "spells": [
            3,
            2,
            2,
            0,
            0,
            0
          ]
        }
      },
      {
        "experiencePoints": 90000,
        "hitPoints": "8d6",
        "otherAbilities": {
          "spells": [
            3,
            2,
            2,
            1,
            0,
            0
          ]
        }
      },
      {
        "experiencePoints": 180000,
        "hitPoints": "9d6",
        "otherAbilities": {
          "spells": [
            3,
            3,
            2,
            2,
            0,
            0
          ]
        }
      },
      {
        "experiencePoints": 270000,
        "hitPoints": "9d6+1",
        "otherAbilities": {
          "spells": [
            3,
            3,
            2,
            2,
            1,
            0
          ]
        }
      },
      {
        "experiencePoints": 360000,
        "hitPoints": "9d6+2",
        "otherAbilities": {
          "spells": [
            4,
            3,
            3,
            2,
            2,
            0
          ]
        }
      },
      {
        "experiencePoints": 450000,
        "hitPoints": "9d6+3",
        "otherAbilities": {
          "spells": [
            4,
            4,
            3,
            2,
            2,
            1
          ]
        }
      },
      {
        "experiencePoints": 540000,
        "hitPoints": "9d6+4",
        "otherAbilities": {
          "spells": [
            4,
            4,
            3,
            3,
            2,
            2
          ]
        }
      },
      {
        "experiencePoints": 630000,
        "hitPoints": "9d6+5",
        "otherAbilities": {
          "spells": [
            4,
            4,
            4,
            3,
            2,
            2
          ]
        }
      },
      {
        "experiencePoints": 720000,
        "hitPoints": "9d6+6",
        "otherAbilities": {
          "spells": [
            4,
            4,
            4,
            3,
            3,
            2
          ]
        }
      },
      {
        "experiencePoints": 810000,
        "hitPoints": "9d6+7",
        "otherAbilities": {
          "spells": [
            5,
            4,
            4,
            3,
            3,
            2
          ]
        }
      },
      {
        "experiencePoints": 900000,
        "hitPoints": "9d6+8",
        "otherAbilities": {
          "spells": [
            5,
            5,
            4,
            3,
            3,
            2
          ]
        }
      },
      {
        "experiencePoints": 990000,
        "hitPoints": "9d6+9",
        "otherAbilities": {
          "spells": [
            5,
            5,
            4,
            4,
            3,
            3
          ]
        }
      },
      {
        "experiencePoints": 1080000,
        "hitPoints": "9d6+10",
        "otherAbilities": {
          "spells": [
            6,
            5,
            4,
            4,
            3,
            3
          ]
        }
      },
      {
        "experiencePoints": 1170000,
        "hitPoints": "9d6+11",
        "otherAbilities": {
          "spells": [
            6,
            5,
            5,
            4,
            3,
            3
          ]
        }
      }
    ]
  },
  {
    "name": "Fighter",
    "description": "Fighters include soldiers, guardsmen, barbarian warriors, and anyone else for whom fighting is a way of life. They train in combat, and they generally approach problems head-on, weapon in hand.\nNot surprisingly, Fighters are the best at fighting of all the classes. They are also the hardiest, able to take more punishment than any other class. Although they are not skilled in the ways of magic, Fighters can nonetheless use many magic items, including but not limited to magical weapons and armor.\nThe Prime Requisite for Fighters is Strength; a character must have a Strength score of 9 or higher to become a Fighter. Members of this class may wear any armor and use any weapon.",
    "restrictions": [
      {
        "restrictionType": "minimum-ability",
        "type": "strength",
        "value": 9
      }
    ],
    "levelData": [
      {
        "experiencePoints": 0,
        "hitPoints": "1d8"
      },
      {
        "experiencePoints": 2000,
        "hitPoints": "2d8"
      },
      {
        "experiencePoints": 4000,
        "hitPoints": "3d8"
      },
      {
        "experiencePoints": 8000,
        "hitPoints": "4d6"
      },
      {
        "experiencePoints": 16000,
        "hitPoints": "5d8"
      },
      {
        "experiencePoints": 32000,
        "hitPoints": "6d8"
      },
      {
        "experiencePoints": 64000,
        "hitPoints": "7d8"
      },
      {
        "experiencePoints": 120000,
        "hitPoints": "8d8"
      },
      {
        "experiencePoints": 240000,
        "hitPoints": "9d8"
      },
      {
        "experiencePoints": 360000,
        "hitPoints": "9d8+2"
      },
      {
        "experiencePoints": 480000,
        "hitPoints": "9d8+4"
      },
      {
        "experiencePoints": 600000,
        "hitPoints": "9d8+6"
      },
      {
        "experiencePoints": 720000,
        "hitPoints": "9d8+8"
      },
      {
        "experiencePoints": 840000,
        "hitPoints": "9d8+10"
      },
      {
        "experiencePoints": 960000,
        "hitPoints": "9d8+12"
      },
      {
        "experiencePoints": 1080000,
        "hitPoints": "9d8+14"
      },
      {
        "experiencePoints": 1200000,
        "hitPoints": "9d8+16"
      },
      {
        "experiencePoints": 1320000,
        "hitPoints": "9d8+18"
      },
      {
        "experiencePoints": 1440000,
        "hitPoints": "9d8+20"
      },
      {
        "experiencePoints": 1560000,
        "hitPoints": "9d8+22"
      }
    ]
  },
  {
    "name": "Magic-User",
    "description": "Magic-Users are those who seek and use knowledge of the arcane. They do magic not as the Cleric does, by faith in a greater power, but rather through insight and understanding.\nMagic-Users are the worst of all the classes at fighting; hours spent studying massive tomes of magic do not lead a character to become strong or adept with weapons. They are the least hardy, equal to Thieves at lower levels but quickly falling behind.\nThe Prime Requisite for Magic-Users is Intelligence; a character must have an Intelligence score of 9 or higher to become a Magic-User. The only weapons they become proficient with are the dagger and the walking staff (or cudgel). Magic-Users may not wear armor of any sort nor use a shield as such things interfere with spellcasting.\nA first level Magic-User begins play knowing read magic and one other spell of first level. These spells are written in a spellbook provided by their master. The GM may roll for the spell, assign it as they see fit, or allow the player to choose it, at their option. See the Spells section for more details.",
    "restrictions": [
      {
        "restrictionType": "minimum-ability",
