=== TheVirtuoid/FunWithJavaScript-Public/games/rpg/databases/schemas/RaceData.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "RaceData Schema",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "weight": {
      "type": "number"
    },
    "height": {
      "type": "number"
    },
    "age": {
      "type": "number"
    },
    "language": {
      "type": "string"
    },
    "classes": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "restrictions": {
      "type": "array",
      "items": {
        "type": "object"
      }
    },
    "specialAbilities": {
      "type": "array",
      "items": {
        "type": "object"
      }
    },
    "savingThrows": {
      "type": "array",
      "items": {
        "type": "object"
      }
    },
    "id": {
      "type": "string"
    }
  }
}

=== TheVirtuoid/FunWithJavaScript-Public/games/rpg/databases/race.json
[
  {
    "name": "Dwarf",
    "description": "Dwarves are a short, stocky race; both male and female Dwarves stand around four feet tall and typically weigh around 120 pounds. Their long hair and thick beards are dark brown, gray or black. They take great pride in their beards, sometimes braiding or forking them. They have a fair to ruddy complexion. Dwarves have stout frames and a strong, muscular build. They are rugged and resilient, with the capacity to endure great hardships. Dwarves are typically practical, stubborn and courageous. They can also be introspective, suspicious and possessive. They have a lifespan of three to four centuries.",
    "weight": 120,
    "language": "dwarvish",
    "height": 48,
    "age": 400,
    "classes": [
      "fighter",
      "cleric",
      "thief"
    ],
    "restrictions": [
      {
        "type": "ability",
        "value": "con",
        "min": 9
      },
      {
        "type": "ability",
        "value": "cha",
        "max": 17
      },
      {
        "type": "weapon-size",
        "value": ["S", "M"]
      }
    ],
    "specialAbilities": [],
    "savingThrows": [
      {
        "attribute": "death-poison",
        "bonus": 4
      },
      {
        "attribute": "wands",
        "bonus": 4
      },
      {
        "attribute": "paralyze-stone",
        "bonus": 4
      },
      {
        "attribute": "spells",
        "bonus": 4
      },
      {
        "attribute": "dragon-breath",
        "bonus": 3
      }
    ]
  },
  {
    "name": "Elf",
    "description": "Elves are a slender race, with both males and females standing around five feet tall and weighing around 130 pounds. Most have dark hair, with little or no body or facial hair. Their skin is pale, and they have pointed ears and delicate features. Elves are lithe and graceful. They have keen eyesight and hearing. Elves are typically inquisitive, passionate, self-assured, and sometimes haughty. Their typical lifespan is a dozen centuries or more.",
    "weight": 130,
    "language": "elvish",
    "height": 60,
    "age": 1200,
    "classes": [
      "fighter",
      "cleric",
      "magic-user",
      "fighter:magic-user",
      "magic-user:thief"
    ],
    "restrictions": [
      {
        "type": "ability",
        "value": "int",
        "min": 9
      },
      {
        "type": "ability",
        "value": "con",
        "max": 17
      },
      {
        "type": "hit-points",
        "value": "1d6"
      }
    ],
    "specialAbilities": [],
    "savingThrows": [
      {
        "attribute": "wands",
        "bonus": 2
      },
      {
        "attribute": "paralyze-stone",
        "bonus": 1
      },
      {
        "attribute": "spells",
        "bonus": 2
      }
    ]
  },
  {
    "name": "Halfling",
    "description": "Halflings are small, slightly stocky folk who stand around three feet tall and weigh about 60 pounds. They have curly brown hair on their heads and feet, but rarely have facial hair. They are usually fair skinned, often with ruddy cheeks. Halflings are remarkably rugged for their small size. They are dexterous and nimble, capable of moving quietly and remaining very still. They usually go barefoot. Halflings are typically outgoing, unassuming and good-natured. They live about a hundred years.",
    "weight": 60,
    "height": 36,
    "age": 100,
    "language": "halfling",
    "classes": [
      "fighter",
      "cleric",
      "thief"
    ],
    "restrictions": [
      {
        "type": "ability",
        "value": "dex",
        "min": 9
      },
      {
        "type": "ability",
        "value": "str",
        "max": 17
      },
      {
        "type": "hit-points",
        "value": "1d6"
      },
      {
        "type": "weapon-size",
        "value": ["S", "M"]
      }
    ],
    "specialAbilities": [],
    "savingThrows": [
      {
        "attribute": "death-poison",
        "bonus": 4
      },
      {
        "attribute": "wands",
        "bonus": 4
      },
      {
        "attribute": "paralyze-stone",
        "bonus": 4
      },
      {
        "attribute": "spells",
        "bonus": 4
      },
      {
        "attribute": "dragon-breath",
        "bonus": 3
      }
    ]
  },
  {
    "name": "Human",
    "description": "Humans come in a broad variety of shapes and sizes; the Game Master must decide what sorts of Humans live in the game world. An average Human male in good health stands around six feet tall and weighs about 175 pounds, while females average five feet nine inches and weigh around 145 pounds. Most Humans live around 75 years.",
    "weight": 165,
    "height": 72,
    "age": 75,
    "language": "human",
    "classes": [
      "fighter",
      "cleric",
      "thief",
      "magic-user",
      "fighter:magic-user",
      "magic-user:thief"
    ],
    "restrictions": [],
    "specialAbilities": [],
    "savingThrows": []
  }
]
